language: ruby
rvm:
  - 1.9.3
script:
  - "firefox --version"
  - DISPLAY=:99.0 bundle exec fudge build
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  global:
    - DISPLAY=:99.0
